[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sled = "0.34.2"
anyhow = "1.0.75"
dotenv = "0.15.0"
oauth2 = "4.3.0"
imap = "3.0.0-alpha.10"
native-tls = "0.2.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
webbrowser = "0.8.11"
tiny_http = "0.12.0"
