[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sled = "0.34.2"
anyhow = "1.0.75"
dotenv = "0.15.0"
async-imap = "0.9.1"
oauth2 = "4.3.0"
tokio-native-tls = "0.3.1"
