[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sled = "0.34.2"
imap = "3.0.0-alpha.10"
lettre = "0.10.4"
anyhow = "1.0.75"
oauth2 = "4.3.0"
dotenv = "0.15.0"
